### ISSUE TITLE
Provider with a self-signed SSL certificate

### ISSUE THREAD

**Issue by stephenllai** [nov/openid_connect#32]
I use the Gem openid_connect to build a RP.  And, the Provider (an existing one) is using a self-signed SSL certificate.

In such scenario, the Gem openid_connect (used in the RP) always gives the SSL verification error.  Only when the Provider is equipped with a trusted SSL certificate, the error no longer occurs.

However, I cannot force all Providers to have trusted SSL certificates.

How can I make the Gem trust all SSL certificates?  (For example, in Excon, the statement "Excon.defaults[:ssl_verify_peer] = false" makes all SSL certificates be trusted, although it will then be less secure.)

**Comment by Hansa064** [comment]
I'm having the same problem here. The problem is, that the httpclient lib uses their own certificates, that get shipped with the gem. They to provide a method "add_trust_ca" to add additional trusted CA's but this method is not called by openid_connect. This problem is also "documented" in their code here https://github.com/nahi/httpclient/blob/master/lib/httpclient/ssl_config.rb

># Represents SSL configuration for HTTPClient instance.
># The implementation depends on OpenSSL.
>#
># == Trust Anchor Control
>#
># SSLConfig loads 'httpclient/cacert.pem' as a trust anchor
># (trusted certificate(s)) with add_trust_ca in initialization time.
># This means that HTTPClient instance trusts some CA certificates by default,
># like Web browsers.  'httpclient/cacert.pem' is downloaded from curl web
># site by the author and included in released package.
>#
># On JRuby, HTTPClient uses Java runtime's trusted CA certificates, not
># cacert.pem by default. You can load cacert.pem by calling
># SSLConfig#load_trust_ca manually like:
>#
>#   HTTPClient.new { self.ssl_config.load_trust_ca }.get("https://...")
>#
># You may want to change trust anchor by yourself.  Call clear_cert_store
># then add_trust_ca for that purpose.

Could you please add an opertunity to add custom trusted CA's?

**Comment by nov** [comment]
you can do so like this.
https://github.com/nov/openid_connect/blob/master/spec/openid_connect_spec.rb#L45
