### ISSUE TITLE
HTTP timeout configuration

### ISSUE THREAD

**Issue by calh** [nov/openid_connect#65]
Hi @nov,

Is there a convenient way to adjust the HTTP timeout settings for discovery / code exchange hits?  The default value of 60s is way too long.  One of our providers had a network issue and all of the 60s timeouts crushed our servers.  I monkeypatched HTTPClient::SessionManager.initialize to override `@connect_timeout` for a quick workaround.

Is there anything better than that for configuration options?

Thanks!

**Comment by nov** [comment]
Hi, you can configure HTTPClient gem config within this gem only context like below.

```ruby
OpenIDConnect.http_config do |c|
  c.connect_timeout = 15
  c.send_timeout    = 15
  c.receive_timeout = 15
end

c = OpenIDConnect.http_client
c.connect_timeout # => 15
c.send_timeout    # => 15
c.receive_timeout # => 15
```

NOTE: since this gem is heavily based on my `rack-oauth2` gem, changing OpenIDConnect gem's http config also changes Rack::OAuth2 gem's http config.
ref.) https://github.com/nov/openid_connect/blob/master/lib/openid_connect.rb#L79

**Comment by calh** [comment]
Thank you!  I've submitted a PR to you and added some extra documentation to your README.
