### ISSUE TITLE
OIDC Provider app broken on Heroku

### ISSUE THREAD

**Issue by kyleboe** [nov/openid_connect#70]
Hitting https://connect-op.herokuapp.com/ I just get:

![image](https://user-images.githubusercontent.com/4054771/182937290-37414be4-b7e2-4511-814b-3e0d8fd7849a.png)

Possibly related to #71

**Comment by willdowglas** [comment]
That is because Heroku stopped the free tier.

You can read more about it here: https://blog.heroku.com/next-chapter.

To keep Heroku running in open-source projects, the maintainer must email them, as you can read in this quote:

> [Open Source Support](https://blog.heroku.com/next-chapter#open-source-support)
We are continuing our involvement in open source. Salesforce is proud of the impactful contribution we’ve made with [Cloud Native Buildpacks](https://buildpacks.io/). We are maintainers of the Buildpacks project, which takes your application source code and produces a runnable OCI image. The project was contributed to the CNCF [Sandbox in 2018](https://www.cncf.io/blog/2018/10/03/cncf-to-host-cloud-native-buildpacks-in-the-sandbox/) and graduated to [Incubation in 2020](https://www.cncf.io/blog/2020/11/18/toc-approves-cloud-native-buildpacks-from-sandbox-to-incubation/). For most Heroku users, Buildpacks remove the worry about how to package your application for deployment, and we are expanding our use of Buildpacks internally in conjunction with our Kubernetes-based [Hyperforce](https://www.salesforce.com/products/platform/hyperforce/) initiative. For a more technical Hyperforce discussion, click [here](https://youtu.be/Q3Uj1rsmFLw?t=858).
>
>If you are a maintainer on an open source project, and would like to request Heroku support for your project, [contact](mailto:ospo-heroku-credits@salesforce.com) the Salesforce Open Source Program office.
